---
apiVersion: v1
kind: Service
metadata:
  name: image-mapper-webhook
  namespace: default
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 2443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: image-mapper-webhook
  namespace: default
subsets:
- addresses:
  - ip: ${HOST_IP}
  ports:
  - port: 2443
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: image-mapper-webhook
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: image-mapper-webhook
  namespace: default
spec:
  dnsNames:
  - image-mapper-webhook
  - image-mapper-webhook.default
  - image-mapper-webhook.default.svc
  - image-mapper-webhook.default.svc.cluster.local
  issuerRef:
    name: image-mapper-webhook
  secretName: image-mapper-webhook
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: image-mapper-webhook
  annotations:
    cert-manager.io/inject-ca-from: default/image-mapper-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: image-mapper-webhook
      namespace: default
      path: /core/v1/pod/mutate
      port: 443
  name: mutate.pods.core.k8s.io
  rules:
  - apiGroups:
    - ''
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: Namespaced
  objectSelector:
    matchExpressions:
    - key: image-mapper.cs.sap.com/ignored
      operator: NotIn
      values:
      - 'true'
    - key: image-mapper.cs.sap.com/disabled
      operator: NotIn
      values:
      - 'true'
  namespaceSelector:
    matchExpressions:
    - key: image-mapper.cs.sap.com/ignored
      operator: NotIn
      values:
      - 'true'
    - key: image-mapper.cs.sap.com/disabled
      operator: NotIn
      values:
      - 'true'
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
  matchPolicy: Equivalent
  sideEffects: None
  timeoutSeconds: 10
  failurePolicy: Fail
  reinvocationPolicy: IfNeeded
